@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor Alice #red

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml